### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by boramalper** [boramalper/magnetico#140]
> Magneticow looks like not support the search of chinese, maybe more language? Could please support that?
>
> -[276562578](https://gitter.im/magnetico-dev/magnetico-dev)

Add internalisation support!

**Comment by alcalyn** [comment]
I already mounted and used an instance of Weblate (https://weblate.org), and I guess it could be a good solution.

We can host our main instance, or, if we talk to them, they can offer us an account on they main instance (because magnetico is a free software), with at least these advantages:

- avoiding to host our own instance
- gain in visibility (I discovered projects on their main instance I like to contribute to translations times to times)

**Comment by DKingCN** [comment]
I tested the case with Chinese input.
Chinese search seems to be **partially** supported.
Only a very few magnet data can be filtered out. I think it's the problem of magnet data encoding.
Input is always utf8 (parsed by flask) while the magnet data in sqlite db varies. (**I GUESS SO**. not verified)

So to solve this situation, magnet data might need to be encoded as a unified charset encoding such as utf8 or whatever.

**Comment by boramalper** [comment]
I've tried with Korean characters and the most recent `go-rewrite` version seems to work.

![mtc1](https://user-images.githubusercontent.com/5618038/44709871-5ebb4800-aab3-11e8-977c-7d023283e26e.png)

Feel free to re-open the issue if you think the issue persist, but the Python version is soon to be abandoned and won't be fixed.
