### ISSUE TITLE
Keeps running, does not find any torrents!

### ISSUE THREAD

**Issue by twisp007** [boramalper/magnetico#145]
$ magneticod --node-addr [my ip]:61221
2017-08-21 15:51:59,469  INFO      magneticod v0.6.0 started
2017-08-21 15:51:59,475  INFO      uvloop is in use
2017-08-21 15:51:59,476  INFO      SybilNode [removed] initialized!
2017-08-21 15:51:59,480  INFO      SybliNode is launched on ('<my ip>', 61221)!

Even after an hour nothing happens.
magneticow says 0 torrents available. 

Checking if the connection is open:
$ netstat -lntu
udp        0      0 [my ip]:61221    0.0.0.0:*

My VPS shows that bandwidth is being utilized like 1 GB for an hour I wonder what that is...

How could I start to debug this?

**Comment by twisp007** [comment]
It was on Manjaro. Now running it on Debian 9. Works fine.

Wonder what's wrong in Manjaro.

**Comment by skobkin** [comment]
Maybe port which was used by `magneticod` DHT was closed by firewall?

**Comment by farmwald** [comment]
I have a similar problem on Ubuntu 8.10.
I only get two torrents. It's been running a while.

**Comment by farmwald** [comment]
I left it running for the last day or so. Less than 500 torrents so far. Is there a problem with my setup or with the algorithm?

**Comment by boramalper** [comment]
The situation shall be better now that I've implemented BEP 51: DHT Infohash Indexing. But if you still encounter the same issue, there are a few things to check:

1. It works best on a VPS/dedicated servers from a cloud provider. Your internet connection at home might be insufficient for contacting DHT nodes reliably I am afraid (NAT being an example).
   - You might still check your port forwarding settings to make sure other nodes can access you through UDP.
2. You would like to disable iptables conntrack for the port you use to prevent EPERM errors (and reduce the load on your machine). See https://github.com/boramalper/magnetico/blob/master/cmd/magneticod/README.md#setup

If the problem persists, please feel free to open a new issue! Closing this one due to age & presuming it's fixed.
