### ISSUE TITLE
Can you tell magnetico where the db is? [moving db]

### ISSUE THREAD

**Issue by blimeybloke** [boramalper/magnetico#152]
Logged into my vm today to see that /root was out of harddrive space due to the magnetico db being 17gb.  Can I move the db to /home and tell magnetico via command where the db is?

**Comment by boramalper** [comment]
Hey @blimeybloke,

you should be able to find the `database.sqlite3` file under `~/.local/share/magneticod/` directory. If there are `database.sqlite3-shm` `database.sqlite3-wal` files as well, I'd suggest you to use the command line `sqlite3` tool to open & close the `database.sqlite3`, so that the log files can be properly handled, lest you might have a data loss/corruption I'm afraid (though I think you can also copy all three to a new directory).

Best,
Bora
