### ISSUE TITLE
Add compiled release

### ISSUE THREAD

**Issue by Snake87r** [boramalper/magnetico#191]
Hello,
It's possible to add in the release package a compiled versione of magneticod and magneticow for Raspberry Pi, because the binary distribuited doesn't work on it.

This is the CPU type of Raspberry Pi 3
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model name:            ARMv7 Processor rev 4 (v7l)

**Comment by skobkin** [comment]
We can use CodeShip (or other free-for-opensource CI) to make automatic build and upload them to Github.

**Comment by boramalper** [comment]
@skobkin Apparently GoReleaser does not support cgo, which we depend on for SQLite3 support (see [mattn/go-sqlite3](https://github.com/mattn/go-sqlite3), so that's out of question.

If you check the [Makefile](https://github.com/boramalper/magnetico/blob/master/Makefile), you'll see two targets `magneticod` and `magneticow`, which has compilation commands. You can cross-compile by setting the following environment variables `GOARM`, `GOARCH`, and `GOOS`. See [gobot documentation](https://gobot.io/documentation/platforms/raspi/). Hence to compile **magneticod** for instance, you use

```bash
GOARM=6 GOARCH=arm GOOS=linux go install --tags fts5 "-ldflags=-s -w -X main.compiledOn=`date -u +%Y-%m-%dT%H:%M:%SZ`" github.com/boramalper/magnetico/cmd/magneticod
```

Honestly I think that's a great idea, but don't know how to _test_ it so I don't want to (officially) support something I can't test. The closest I can think of is ARM-powered A1 instances on AWS, but that's not an automated solution (and it's still not a Raspberry Pi).

I am closing the issue as there are currently no solutions, and that now you know how to cross-compile yourself. Feel free to continue the discussion, or create a new issue/pull request if you find a solution.

**Comment by skobkin** [comment]
> The closest I can think of is ARM-powered A1 instances on AWS

You can also check Scaleway's [ARM](https://www.scaleway.com/en/pricing/#anchor_arm) and [Baremetal Arm](https://www.scaleway.com/en/pricing/#anchor_baremetal) instances. Both can be created and deployed via API (AWS also can be deployed automatically too).

**Comment by ad-m** [comment]
Drone.io is CI provider which support ARM & free for open-source.

**Comment by rezad1393** [comment]
can this be opened?
I dont seem to be able make the package on my arm system

**Comment by skobkin** [comment]
> I dont seem to be able make the package on my arm system

As a workaround you can try to use Dockerfile to build it inside Docker.

**Comment by rezad1393** [comment]
> > I dont seem to be able make the package on my arm system
> 
> As a workaround you can try to use Dockerfile to build it inside Docker.

how would I do that?
I am barely familiar with Docker and can just run copy and paste for that.
and I checked dokcer repo for it and it was only x64.

**Comment by skobkin** [comment]
> how would I do that?

You'd need to check Docker manual or search for something like "how to build Docker image".

> and I checked dokcer repo for it and it was only x64

That's why I suggested to use Dockerfile and not an image from the Docker Hub. It's not bound to the architecture and if you have an ARM machine, you can build your own image for ARM. Or you can use cross-compile on X86, but it's much more complicated that previous option.

**Comment by rezad1393** [comment]
As I said I didnt see any docker make file for arm for this and outside of go make (make) there is no readme to how to compile it.
