### ISSUE TITLE
Timeline on BEP 51 (infohash indexing) implementation?

### ISSUE THREAD

**Issue by jbruchon** [boramalper/magnetico#196]
I have noticed that `magneticod` is extremely slow to collect torrent information. Is there a timeline for completing BEP 51 implementation? All development seems to have ground to a halt shortly after the "start working on BEP 51" commit.

**Comment by boramalper** [comment]
The development has never been halted yet I am quite busy with university so I don't have time to work on magnetico (or any other "big" projects). Though now that I am done with exams, I am planning to get back to it!

Indeed, I have just released v0.8.0 which features BEP 51 Infohash Indexing. The performance seemed quite satisfactory to me (~8000 per *hour*), but do share your opinions too! =)

Closing the issue since it's implemented now.

**Comment by jbruchon** [comment]
Thanks so much for this! I brought up this program on r/DataHoarder and several people were interested in it, so this is wonderful to see! I couldn't compile this under the latest gccgo (I don't have the `dep` tool) but the binary release is plenty good for me.

**Comment by boramalper** [comment]
Again, with v0.8.0, I moved from `dep` to Go modules so you might want to try again. Of course static binaries and (even better) Docker images are available too.
