### ISSUE TITLE
webUI not showing results

### ISSUE THREAD

**Issue by roboticsound** [boramalper/magnetico#31]
I'm not sure what I'm doing wrong but magneticod is finding results but when I search in the webUI, nothing is showing. Running Ubuntu Server 16.04. Let me know if I can provide more details.

**Comment by boramalper** [comment]
> Let me know if I can provide more details.

Please. =)

How long did you wait before using the webUI? Because **magneticod** commits torrents to the database in dozens so you have to wait until it finds its first a dozen torrent.

Also, in my case for instance, **magneticow** is so so slow; it easily takes 30-50 seconds for a simple query, which is very annoying. If that's what you meant, I'll also have a look at that in future.

**Comment by boramalper** [comment]
Hello @roboticsound! I think the issue you raised must be solved by now hence I'm closing the issue. Feel free to comment if you think it persists.

Thanks for spending your time to report the issue!
