### ISSUE TITLE
include search APIs in magneticow to support third party search apps

### ISSUE THREAD

**Issue by lozbrown** [boramalper/magnetico#50]
its reasonably common to use clients like transdroid
erickok/transdroid
erickok/transdroid-search

it would be nice if there was an API (usually some sort of XML API) in magneticow that enables us to search from a remote client application. 

I've raised a similar issue in transdroid-search 
erickok/transdroid-search#57 @erickok

**Comment by boramalper** [comment]
You can check my comment on the referenced issue.

**Comment by ngosang** [comment]
Restful JSON API instead of XML API.

**Comment by scriptzteam** [comment]
You can try this one -> 

Base-page:
https://dht.bittor.ch/

Base-page search:
https://dht.bittor.ch/?search=ubuntu

Base-RSS:
https://dht.bittor.ch/rss

Base-RSS search:
https://dht.bittor.ch/rss?search=ubuntu

Base-RSS search with limits number of output:
https://dht.bittor.ch/rss?search=ubuntu&limit=5

**Comment by scriptzteam** [comment]
Json-API with search and limit output (limit can be max. 100):
https://dht.bittor.ch/api?search=ubuntu&limit=3

Json-API latest 1000:
https://dht.bittor.ch/api

**Comment by ad-m** [comment]
I believe webscoket streaming API might be useful too. See for example  https://dev.twitter.com/streaming/overview . This will open new opportunities for conducting research on the DHT network. For example by tracking infringements (for example new movie releases by keyword "CAM 2017" or episode series) as soon as occurs. This will open up new use cases for torrent network too.

**Comment by ad-m** [comment]
I would like make awareness [BEP-36 Torrent RSS feeds](http://www.bittorrent.org/beps/bep_0036.html). It might be useful.

**Comment by boramalper** [comment]
Request for comment! Commit 5e5d152 has the initial proposal for the REST-ful HTTP API of **magneticow**. Check [**magnetico<sup>w</sup>** API Documentation](https://github.com/boramalper/magnetico/blob/master/magneticow/docs/API/README.md) and [**magnetico<sup>w</sup>** API v0 Documentation](https://github.com/boramalper/magnetico/blob/master/magneticow/docs/API/v0.md) for proposals.

**Comment by erickok** [comment]
Generally seems fine, if sparse. Not sure what info you have but transdroid-search would like more info on the torrent such as torrent download size and number of seeders/leechers. (Sorry for being ignorant about the magnetico details.)

**Comment by boramalper** [comment]
@erickok Thanks for the feedback! Yeah, there is still lots of room for precision and elaboration, but I wanted to outline the spec for some initial feedback.

Torrent download size, number of files, etc. are easy to add, **but**, number of seeders/leechers without relying on a central tracker is **hard**. Even those numbers are "local", in the sense that, each tracker can keep track of seeders and leechers only if they contact the tracker. Nevertheless, this requires implementing [BEP 33](http://www.bittorrent.org/beps/bep_0033.html) and definitely is in our list. =)

**Comment by boramalper** [comment]
BEP 36 (Torrent RSS feeds) is now implemented in **magneticow**. =) /cc @ad-m

**Comment by ad-m** [comment]
I see. We have feed and we have security issue due lack authentication test on ``/feed`` route.

**Comment by boramalper** [comment]
@ad-m Sort of:

**magneticow** uses basic access authentication for everything and it worked reasonably well to secure the web interface from intruders yet being simple. Now that we implemented feeds, basic access authentication (BAA) doesn't go well with BitTorrent clients. qBittorrent supports cookies but not BAA. I don't know the case with Deluge, uTorrent and other clients but I doubt if it's different.

Nevertheless, the current approach works well, considering that it's a trade-off. Currently, any requests for `/feed` requires `hash` parameter, that is the hex encoding of sha256 sum of `USERNAME\0PASSWORD\0FILTER`. It works well because:

* It protects the `/feed` from the outside world.
* The hash is persistent through the restarts (so when you update or restart **magneticow**, nothing will be affected).
* The hash is different for each `filter` (*i.e.* query) so that you cannot use the same hash for all feed subscriptions (just in case if the URL leaks).

The same approach is used by TorrentLeech as well, although you can reset your "hash" there (in case of **magneticow**, you need to change your username or password).

**Comment by ad-m** [comment]
@boramalper , you are right. I miss that. I am sorry.

**Comment by boramalper** [comment]
@ad-m No problem at all, thanks for caring about the project in the first place. =)

**Comment by boramalper** [comment]
See #162!
