### ISSUE TITLE
 CPU performance optimalization (again)

### ISSUE THREAD

**Issue by ad-m** [boramalper/magnetico#61]
Hello,

When application started and indexing bootstraped there is 100% CPU usage, so the indexing speed is CPU-limited mostly, so if we want more effective software we need start optimizing of CPU usage again.

I reported earlier this kind of issue (#41), some changes was prepared (#43), next to memory limitation was fixed (#58). There is CPU-bounding again. If we want improve throughput which I believe is our goal (see #60) we need improve CPU computation again. 

Remove bottle-neck to improve throughput is continuous and iterative process. I would like starts public discussion about possible optimization again.

I am using single-core machine, so believe there is no mention of multiple processes disused in some issue. Alternatively, distributed processing would be applicable. Probably using the mechanisms similar to multiprocessing.

Here is graph of network & cpu & memory usage:

![grafana_-_magnetico_performance_-_2017-05-01_02 06 11](https://cloud.githubusercontent.com/assets/3618479/25569209/c64ea378-2e12-11e7-8c7e-f08793340b06.png)

Current indexing speed on my machine is 2-4 magnet / s. (120-240/ min.).

Greetings,

**Comment by ad-m** [comment]
Here is up-to-date profiling graph (includes # 60 , # 59 , # 58 , # 56 ):

![graph](https://cloud.githubusercontent.com/assets/3618479/25569435/c3897596-2e17-11e7-9db0-e505e22cba8f.png)

**Comment by ad-m** [comment]
And up to date memory usage graph:
![dane](https://cloud.githubusercontent.com/assets/3618479/25569489/b59dd804-2e18-11e7-988d-6f210ef279a9.png)
Data are from different samples.

**Comment by ngosang** [comment]
I think memory usage is acceptable and most CPU usage is spend in network related so it's ok. We can do some improvements replacing all bencode calls with custom code as I did #43. Also I think SQLite is a bottle neck and we should use another DB. Check => https://github.com/boramalper/magnetico/issues/41#issuecomment-294849473

**Comment by boramalper** [comment]
@ngosang 

> I think memory usage is acceptable and most CPU usage is spend in network related so it's ok.

I agree. I'll take a deeper look using a line profiler to detect bottlenecks more precisely, but in the graph @ad-m shared above, most of the time is spent in `sendto` and `__random_bytes`. Not sure what can be done for the first one (or if asyncio + uvloop would help or not) but we can send the same "random" bytes for all the messages, or at least use something faster. I think `random` module was a right choice, but instead of using `getrandbits()` we should've used something like `"".join(chr(random.randint(0,255)) for _ in range(4))`. I'll profile them as well, instead of speculating, so that we can solve this issue for once and ever. =)
 
> Also I think SQLite is a bottle neck and we should use another DB. Check => #41 (comment).

The problem was related to **magneticow** full-text queries, which are solved in v0.3.0. It was due to a very silly bug, that is, we re-opened database *every single time* a request is made, which was obviously slow as hell. Now it's performing quite well. Memory usage of **magneticod**, if desired, can be reduced even further by removing [the line 219 in magneticow.py](https://github.com/boramalper/magnetico/blob/master/magneticow/magneticow/magneticow.py#L219) [which tells SQLite to store the temporary FTS table in memory](https://www.sqlite.org/pragma.html#pragma_temp_store). Probably I'll remove it, as OS should do a better job than us in caching the file in memory.

**Comment by ad-m** [comment]
Are we satisfied with the results of indexing? What actions can we take to improve if we are not satisfied?

@ngosang , i don't think SQLite is a bottle neck. Graphs don't show that. We should rely on data, not feelings. I don't use ``magneticow`` yet. I have concept use ``magnetico`` in unsupported way eg. websockets stream. I will probably reject the current layer of persistence in general in my deployment. SQLite doesn't fit well to distributed processing eg.. webserver & crawler server.

@boramalper , see https://github.com/python-git/python/blob/master/Lib/random.py and https://github.com/python-git/python/blob/715a6e5035bb21ac49382772076ec4c630d6e960/Modules/_randommodule.c to

**Comment by Glandos** [comment]
@ngosang This is a bit old, but the only article I found: http://www.sqlservercentral.com/articles/Performance+Tuning/90243/
SQLite is not so obviously slow. I personnally had to implement it to store a lot of a small files, and it outperforms a lot of other solutions. When the database is single-user single-connection, this is usually a very good choice, unless you need advanced feature like replication. And I agree with @ad-m we should rely on data :)

**Comment by ngosang** [comment]
Ok, insert speed is good enough for magneticod, but I was thinking globally, including searches. We can let this to the future and focus in other optimizations now.

**Comment by ngosang** [comment]
> Current indexing speed on my machine is 2-4 magnet / s. (120-240/ min.).

@ad-m I'm indexing +150/second. I did some modifications in the code you could try. NOTE: I have a very fast CPU but a low speed network (30Mbps). So my bottleneck was UDP congestion, I was losing thousand of packets.
1) I'm using a fixed port (--node-addr) so if I have to restart the daemon, I do in the same port and I don't lose previous neighbors. 
2) I commented this if/else block. I don't know wy but in Windows is not working as intended and self.__n_max_neighbours growth until crash. https://github.com/boramalper/magnetico/blob/818667b3634d56553ff36496141aca4f4d852ea3/magneticod/magneticod/dht.py#L117
3) I reduced tick_intervale to 0.1 my CPU is really fast => https://github.com/boramalper/magnetico/blob/818667b3634d56553ff36496141aca4f4d852ea3/magneticod/magneticod/constants.py#L9
4) I changed self.__n_max_neighbours = 50 or 100 (you have to tune according to your network. Be aware that this number only limits the number of neighbors you contact each tick, you don't need to know all internet. Btw, this constant should be in constants.py => https://github.com/boramalper/magnetico/blob/818667b3634d56553ff36496141aca4f4d852ea3/magneticod/magneticod/dht.py#L48

**Comment by boramalper** [comment]
> I changed self.__n_max_neighbours = 50 or 100 (you have to tune according to your network. Be aware that this number only limits the number of neighbors you contact each tick, you don't need to know all internet. Btw, this constant should be in constants.py => https://github.com/boramalper/magnetico/blob/818667b3634d56553ff36496141aca4f4d852ea3/magneticod/magneticod/dht.py#L48

It's not constant, see https://github.com/boramalper/magnetico/blob/818667b3634d56553ff36496141aca4f4d852ea3/magneticod/magneticod/dht.py#L117

It's changed accordingly to prevent congestion.

----

1. Your first point is very clever! Probably we should mention it somewhere in the docs. =)
2. It's a bug, probably because Windows uses a different way of notifying ICMP source quench messages. (See https://github.com/boramalper/magnetico/blob/818667b3634d56553ff36496141aca4f4d852ea3/magneticod/magneticod/dht.py#L104)

----

Lastly, I should learn about how ICMP quench messages work, so that instead of [clearing the whole outgoing queue](https://github.com/boramalper/magnetico/blob/818667b3634d56553ff36496141aca4f4d852ea3/magneticod/magneticod/dht.py#L118) when congestion happens, we can maybe simply stop communicating with those peers for a while. It's also possible that the remote peer also sent a [`choked` message](https://wiki.theory.org/BitTorrentSpecification#Peer_wire_protocol_.28TCP.29) (using BitTorrent Protocol) so we may pay attention to them as well.

As you can see, it's a bit complicated but I think perfectly manageable. =)

**Comment by ngosang** [comment]
> It's not constant, see https://github.com/boramalper/magnetico/blob/818667b3634d56553ff36496141aca4f4d852ea3/magneticod/magneticod/dht.py#L117
It's changed accordingly to prevent congestion.

It's a constant if you comment the if/else block as I said in 2)

**Comment by ad-m** [comment]
@ngosang, 
> I'm indexing +150/second. I did some modifications in the code you could try. NOTE: I have a very fast CPU but a low speed network (30Mbps). So my bottleneck was UDP congestion, I was losing thousand of packets.

Very interesting! I rent CPU-hog server from Tiktalik.com. I am unable receive any interesting result, due continuous timeout. Tiktalik.com is cheap polish VPS vendor. Next to I rent CPU-hog server from Oktawave.com. This provider has good reviews of high level of service, including networking. I don't have so much timeouts. Unfortunately, it's a bit faster.
```
 Saved 19655 metadata in session 55 minutes and 13.41 seconds long. Average speed was 5.93 metadata / s.
```
Last result was on 1 vCPU machine. Now I have 4 vCPU and I don't have 100% CPU usage and ~0% system time (Earlier it was ~50/50 user time and system time):
![zaznaczenie_0573](https://cloud.githubusercontent.com/assets/3618479/25638362/731e7ff8-2f88-11e7-9308-c82fc9720236.png)

I think it is worthwhile considering in this situation to adapt the application to many processes. We need to consider the issue of sharing Bloom filter and database access. 

SQLite [support single-machine multiple-process database access](https://www.sqlite.org/faq.html#q5) (read and write with locks), so it does not require much customization until we deploy distributed applications to multiple servers.

Bloom filter can be implemented [using Redis](https://github.com/seomoz/pyreBloom). This unfortunately means that running the application will be much more difficult. Perhaps we should support two forms of action - multi-process with Redis server and single-process in-memory. Alternatively, we will have to use another form of shared memory. Alternatively, we will have to use another form of shared memory.

**Comment by boramalper** [comment]
![https://s2.postimg.org/9k5b0blqh/magnetico.png](https://s2.postimg.org/9k5b0blqh/magnetico.png)

Hopefully the latest asyncio re-write solves the issue. Feel free to open more "issues" in future if you would like to reduce it more. I am aware that it is still too high and working on it. =)
